### ISSUE TITLE
What triggers isExpense?

### ISSUE THREAD

**Issue by ruben-with-b** [webschik/mt940-js#15]
Hi @webschik,

I am using your parser, works really well. I was just wondering, what exactly sets `isExpense` `true` or `false`?
When I am parsing a file containing only incomes, `isExpense` still is set `true`.

I saw from your code, that you scan for certain codes (e.g. `'N060'`). So is the array maybe incomplete?
The transaction codes in my file are like 'NMSC' or 'NSTO'.

Cheers

**Comment by ruben-with-b** [comment]
Anything about that..?

**Comment by webschik** [comment]
Hi @ruben-with-b !

`incomeTransactionCodes` list is not complete, indeed.
It's possible to update this list based on codes from https://www-2.danskebank.com/Link/Mt940sapUK/$file/Mt940_sap_UK.pdf, PRs are welcome ;)

Be aware that `NMSC` stands for `Miscellaneous`, so based on this code it's not possible correctly if it's income or expense.
