### ISSUE TITLE
Mostly first transaction in an array of transcations has an amount of 0.

### ISSUE THREAD

**Issue by maartenvandewaarsenburg** [webschik/mt940-js#4]
In these cases also the id, code, valueDate, entryDate and bankReference are empty.

As far as I can see this is true when "isCredit" equals false.

Version: 0.5.0.

**Comment by webschik** [comment]
Hi @maartenvandewaarsenburg!
Could you add an example of your mt940 file?

**Comment by maartenvandewaarsenburg** [comment]
Hello @webschik,

Please find an example attached. As the name says, it's the first statement from the file and also in the history of the bank account. € 100,- has been transferred to the account.
I've also added the json output of the statements returned by the read.



[firstStatement.txt](https://github.com/webschik/mt940-js/files/1179172/firstStatement.txt)
[firstStatement.json.txt](https://github.com/webschik/mt940-js/files/1179195/firstStatement.json.txt)

**Comment by webschik** [comment]
Thank you! I will check it asap

**Comment by webschik** [comment]
This issue is fixed in version 0.5.1
