### ISSUE TITLE
bankReference is empty sometimes

### ISSUE THREAD

**Issue by maartenvandewaarsenburg** [webschik/mt940-js#6]
Hi Denys,

Sometimes the bankReference field is empty although the information is available in the MT940 file. Most often this occurs when the customer reference in the input is available. When that is the case, the customerReference field is also empty.

I sent an example file earlier. Please see bank reference 'B6K21PGKGO755NPK' in that file for an example.

Regards,
Maarten.

**Comment by webschik** [comment]
Thank, Maarten!
This issue is fixed in version 0.5.2
