### ISSUE TITLE
Unique transaction ID generation doesn't work properly.

### ISSUE THREAD

**Issue by Aristona** [webschik/mt940-js#8]
Hi,

Today I found that some of the transactions weren't being added to the database because of the unique constraint. I did some debugging and I found that I two different transactions with the same ID.

Code that generates md5: https://github.com/webschik/mt940-js/blob/9cc924253b9e91006aef4b1fe592a6dd79bd30ca/src/tags/transaction-info.ts#L119

```
 { id: 'a8e3d70ce04262612c44d2a2a3b1898d',
  code: 'N658',
  amount: 550,
  currency: 'EUR',
  isCredit: true,
  isExpense: true,
  entryDate: '2017-03-01',
  fundsCode: '',
  valueDate: '2017-03-01',
  description: 'SOMETHING DIFFERENT 21312312412',
  bankReference: '',
  customerReference: '',
  referenceNumber: 'ABN AMRO BANK NV',
  openingBalance: 
   { isCredit: true,
     date: '2017-02-28',
     currency: 'EUR',
     value: 16489.78 },
  closingBalance: 
   { isCredit: true,
     date: '2017-03-01',
     currency: 'EUR',
     value: 18629.78 } }
```

```
{ id: 'a8e3d70ce04262612c44d2a2a3b1898d',
  code: 'N654',
  amount: 550,
  currency: 'EUR',
  isCredit: true,
  isExpense: false,
  entryDate: '2017-03-01',
  fundsCode: '',
  valueDate: '2017-03-01',
  description: 'SOMETHING DIFFERENT 111231431',
  bankReference: '',
  customerReference: '',
  referenceNumber: 'ABN AMRO BANK NV',
  openingBalance: 
   { isCredit: true,
     date: '2017-02-28',
     currency: 'EUR',
     value: 16489.78 },
  closingBalance: 
   { isCredit: true,
     date: '2017-03-01',
     currency: 'EUR',
     value: 18629.78 } }
```
I deleted sensitive information including the description, but they are completely unrelated, including a different IBAN on both of them.

I'll find the reason of it and create a PR sometime soon.

Ps. It is known that `md5` sometimes generates the same output for different inputs. You may have to change it in the future.

Edit: Actually, the problem is passing the exact same data to the `md5` method.

```
2017-03-01

550,
EUR

Parameter to md5: 2017-03-01550,EUR
Response from md5: a8e3d70ce04262612c44d2a2a3b1898d



2017-03-01

550,
EUR

Parameter to md5: 2017-03-01550,EUR
Response from md5: a8e3d70ce04262612c44d2a2a3b1898d
```

I think we have to include another unique identifier such as description, but it's going to be a breaking change.

I'll create myself a hashing callback and keep the previous one there.

**Comment by webschik** [comment]
Fixed in https://github.com/webschik/mt940-js/pull/9
Please, update to the version 0.6.0 and check the new docs https://github.com/webschik/mt940-js#readoptions
